# Generated by Django 3.2.12 on 2022-04-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('l', 'Faible'), ('a', 'Moyenne'), ('h', 'Haute')], default='a', max_length=1),
        ),
    ]
