# Generated by Django 3.2.12 on 2022-04-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_contributor_unique_project_manager'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('title', 'type'), name='unique_project_type'),
        ),
    ]
